//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class hEmployeeAddress
    {
        public int AddressID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> Type { get; set; }
        public string PrimaryAddress { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Country { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string County { get; set; }
        public string Language { get; set; }
    
        public virtual hEmployee hEmployee { get; set; }
    }
}
