//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class sUserOption
    {
        public int UserID { get; set; }
        public string SetupCode { get; set; }
        public string SetupValue { get; set; }
    
        public virtual sUser sUser { get; set; }
    }
}
