//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class sUser
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public byte[] Password { get; set; }
        public string CustomCriteria { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<bool> Locked { get; set; }
        public string SecretQuestion { get; set; }
        public string SecretAnswer { get; set; }
        public Nullable<System.DateTime> PassEffectiveDate { get; set; }
        public byte[] OldPass1 { get; set; }
        public string OldPass2 { get; set; }
        public string OldPass3 { get; set; }
        public string OldPass4 { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Ldetails { get; set; }
        public string ViewHeirarchy { get; set; }
        public Nullable<int> TAprSupervisorId { get; set; }
        public Nullable<System.DateTime> TAprStartDate { get; set; }
        public Nullable<System.DateTime> TAprEndDate { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
    
        public virtual sUserOption sUserOption { get; set; }
    }
}
