//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MPPLEntities : DbContext
    {
        public MPPLEntities()
            : base("name=MPPLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hEmployee> hEmployees { get; set; }
        public virtual DbSet<hEmployeeAddress> hEmployeeAddresses { get; set; }
        public virtual DbSet<sUserAccess> sUserAccesses { get; set; }
        public virtual DbSet<sUser> sUsers { get; set; }
        public virtual DbSet<sUserOption> sUserOptions { get; set; }
        public virtual DbSet<vEmployee> vEmployees { get; set; }
    }
}
