//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmployee
    {
        public Nullable<int> EMPLOYERID { get; set; }
        public int EMPLOYEEID { get; set; }
        public string EMPLOYEENUMBER { get; set; }
        public string BADGE { get; set; }
        public string EMPNAME { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string BIRTHDATE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string PAYGROUPCODE { get; set; }
        public string PAYGROUPDESC { get; set; }
        public string TIMEGROUPCODE { get; set; }
        public string TIMEGROUPDESC { get; set; }
        public Nullable<System.DateTime> PERIODSTART { get; set; }
        public Nullable<System.DateTime> PERIODEND { get; set; }
        public Nullable<System.DateTime> NEXTSTART { get; set; }
        public Nullable<System.DateTime> NEXTEND { get; set; }
        public string PhoneNo { get; set; }
        public string EMPLOYERDESC { get; set; }
        public Nullable<int> TIMEGROUPID { get; set; }
        public Nullable<int> PAYGROUPID { get; set; }
        public Nullable<int> JOBCODEID { get; set; }
        public string ADDRESS1 { get; set; }
        public string CITY { get; set; }
        public string POSTALCODE { get; set; }
        public string EMPLOYERCODE { get; set; }
        public int LEVEL1 { get; set; }
        public int LEVEL2 { get; set; }
        public int LEVEL3 { get; set; }
        public int LEVEL4 { get; set; }
        public int LEVEL5 { get; set; }
        public int LEVEL6 { get; set; }
        public int LEVEL7 { get; set; }
        public int LEVEL8 { get; set; }
        public int LEVEL9 { get; set; }
        public int LEVEL10 { get; set; }
        public string LEVELCODE1 { get; set; }
        public string LEVELCODE2 { get; set; }
        public string LEVELCODE3 { get; set; }
        public string LEVELCODE4 { get; set; }
        public string LEVELCODE5 { get; set; }
        public string LEVELCODE6 { get; set; }
        public string LEVELCODE7 { get; set; }
        public string LEVELCODE8 { get; set; }
        public string LEVELCODE9 { get; set; }
        public string LEVELCODE10 { get; set; }
        public string JOBCODE { get; set; }
        public string COUNTRY { get; set; }
        public string FLATAMOUNT { get; set; }
        public string SALARIEDHOURLY { get; set; }
        public Nullable<int> FREQUENCYID { get; set; }
        public Nullable<int> TIMESHEETWORKCODEID { get; set; }
        public Nullable<System.DateTime> LASTHIREDATE { get; set; }
        public string MIDDLENAME { get; set; }
        public string SSN { get; set; }
        public int OVERDAY { get; set; }
        public string OVERDAYTIME { get; set; }
        public decimal UNITRATE { get; set; }
        public int EXEMPT { get; set; }
        public System.DateTime ADJSENIORITYDATE { get; set; }
        public Nullable<int> EMPFREQID { get; set; }
        public Nullable<int> EMPLOYEETYPE { get; set; }
        public Nullable<int> SHIFTID { get; set; }
        public string LEVELDESC1 { get; set; }
        public string LEVELDESC2 { get; set; }
        public string LEVELDESC3 { get; set; }
        public string LEVELDESC4 { get; set; }
        public string LEVELDESC5 { get; set; }
        public string LEVELDESC6 { get; set; }
        public string LEVELDESC7 { get; set; }
        public string LEVELDESC8 { get; set; }
        public string LEVELDESC9 { get; set; }
        public string LEVELDESC10 { get; set; }
        public string JOBDESC { get; set; }
        public string LEVEL1CDN { get; set; }
        public string LEVEL2CDN { get; set; }
        public string LEVEL3CDN { get; set; }
        public string LEVEL4CDN { get; set; }
        public string LEVEL5CDN { get; set; }
        public string LEVEL6CDN { get; set; }
        public string LEVEL7CDN { get; set; }
        public string LEVEL8CDN { get; set; }
        public string LEVEL9CDN { get; set; }
        public string LEVEL10CDN { get; set; }
        public string JOBCODECDN { get; set; }
    }
}
